# Test all scripts in tests/ and publish html documentation
image: python:3.8-alpine

test-all-test:
  stage: test
  script:
  - cd tests/
  - pip install scipy
  - python3 test_lbh15_fromX.py -v
  - python3 test_lbh15_static.py -v
  - python3 test_lead_basics.py -v
  tags:
    - newcleo_docker_alpine3.8
    
documentation:
  stage: deploy
  before_script:
    - mkdir public
    - ls -lht
  script:
    - cd docs
    - make html
    - ls -lht _build/html/
    - cd ..
    - cp -r docs/_build/html/* public/
  tags:
  - shell_newcleo
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
