image: python:3.8-alpine

# for testing we do not want to publish pages - just check everything works
test-all-test:
  stage: test
  script:
  - cd test/
  - pip install scipy
  - python3 test_lbh15_fromX.py -v
  - python3 test_lbh15_static.py -v
  - python3 test_lead_basics.py -v
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  tags:
    - newcleo
    
documentation:
  stage: deploy
  before_script:
    - mkdir public
    - ls -lht
  script:
    - cd docs
    - pip install -U sphinx
    - pip install -U numpydoc  
    - pip install -U sphinx-rtd-theme
    - pip install -U myst-parser
    - sphinx-build -b html . _build
    - ls -lht _build
    - cd ..
    - cp -r docs/_build/* public/
  tags:
    - newcleo
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
