test-all-test:
  stage: test
  script:
  - cd tests/
  - python3 test_lbh15_fromX.py -v
  - python3 test_lbh15_static.py -v
  - python3 test_lead_basics.py -v
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  tags:
    - newcleo_shell
    
documentation:
  stage: deploy
  before_script:
    - mkdir public
    - ls -lht
  script:
    - cd docs
    - sphinx-build -b html . _build
    - ls -lht _build
    - cd ..
    - cp -r docs/_build/* public/
  tags:
    - newcleo_shell
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
