# Test all scripts in tests/ and test installation
name: main_actions

on: push

jobs:
  test_all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd && ls -a
