# Test all scripts in tests/ and test installation
name: main_actions

on: push

jobs:
  test_all_tests:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./tests    
    steps:
      - uses: actions/checkout@v3
      - run: pip install scipy
      - run: python3 test_lbh15_fromX.py -v
      - run: python3 test_lbh15_static.py -v
      - run: python3 test_lead_basics.py -v
      - run: python3 test_custom_properties.py -v
      
  test_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install wheel
      - run: pip install .

  test_documentation:
    runs-on: ubuntu-latest    
    defaults: 
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - run: apt-get install python3-sphinx
      - run: make html
      
