# Test all scripts in tests/ and test installation

jobs:
  test_all_tests:
    runs-on: ubuntu-latest
    steps:
      - cd tests/
      - python3 test_lbh15_fromX.py -v
      - python3 test_lbh15_static.py -v
      - python3 test_lead_basics.py -v
      - python3 test_custom_properties.py -v