# Test all scripts in tests/ and test installation
name: main_actions

on: push

jobs:
  test_all_tests:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./tests    
    steps:
      - uses: actions/checkout@v3
      - run: pip install scipy
      - run: python3 test_lbh15_fromX.py -v
      - run: python3 test_lbh15_bounds.py -v
      - run: python3 test_lead_basics.py -v
      - run: python3 test_custom_properties.py -v
      
  test_installation:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install wheel
      - run: pip install .

  test_installation_legacy:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: "3.8.10"
      - run: pip install wheel
      - run: pip install .

  test_documentation:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest    
    defaults: 
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install python3-sphinx
      - run: pip install sphinx-rtd-theme
      - run: pip install myst-parser
      - run: pip install sphinxcontrib-bibtex
      - run: make html
      
