name: Sphinx build

on: 
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      defaults: 
        run:
          working-directory: ./docs
      uses: actions/checkout@v3
      run: sudo apt-get install python3-sphinx
      run: pip install sphinx-rtd-theme
      run: pip install myst-parser
      run: pip install sphinxcontrib-bibtex
      run: make html
      #uses: ammaraskar/sphinx-action@master
      #with:
      #  pre-build-command: pip install sphinx-rtd-theme myst-parser sphinxcontrib-bibtex
      #  docs-folder: "docs/"
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v1
      with:
        path: docs/_build/html/
    - name: Deploy
      uses: actions/deploy-pages@v1
