name: test_build

on: push

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: pip install sphinx-rtd-theme myst-parser sphinxcontrib-bibtex
        docs-folder: "docs/"
