name: test_build

on: push

jobs:
  test_build:    
    runs-on: ubuntu-latest    
    defaults: 
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install python3-sphinx
      - run: pip install sphinx-rtd-theme
      - run: pip install myst-parser
      - run: pip install sphinxcontrib-bibtex
      - run: make html
